### PR TITLE
Full test workflow

### PR DESCRIPTION
**Pull request by ajayyy**

### CODE REVIEW

**Comment by sebastiengrd** [comment]
I get this error when running it. I don't understand why it tries to initialize the sbg and the serial interface, and I think that the logs are different

-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/Users/sebas/OneDrive/Documents/rocket-code-2020/sbgECom/projects/unix
[ 61%] Built target sbgECom
[ 97%] Built target WiringPi
[100%] Built target MainLoop
Initializing TESTING...
Initializing SBG...
create thread
Initializing LOGGER...
sbgInterfaceSerialCreate: Unable to open the com port: /dev/ttyUSB0
create thread
ellipseMinimal: Unable to create the interface.
RocketSM::ExitInit
RocketSM::EnterWaitForInit
158c158
< 177282256244,-114.386,nan,-121.885,610.21,nan,663.584,45.1412,-75.311,87.11,-22.608,-22.608,-1.20858,-0.883102,0.971221,-9.42784,0.12852,-0.169869,258,1,36992,22.039,22.039,54.719,0,500,500,500,1000,1000,1000,6,101597,1023,0.163795,0.00500334,0.00303238,11.907,-9.44163,0.202418,-0.200985,0.142585,0.00522227,0.00494883,
---
> 177282256244,-114.386,-nan,-121.885,610.21,nan,663.584,45.1412,-75.311,87.11,-22.608,-22.608,-1.20858,-0.883102,0.971221,-9.42784,0.12852,-0.169869,258,1,36992,22.039,22.039,54.719,0,500,500,500,1000,1000,1000,6,101597,1023,0.163795,0.00500334,0.00303238,11.907,-9.44163,0.202418,-0.200985,0.142585,0.00522227,0.00494883,

Error in the following file: 0.24.uorocketlog

**Comment by sebastiengrd** [comment]
For the Interface::sensorsInitialized() method, I'm not sure about the logic when TESTING=1. I see two issues with this 

1. It is possible that (for example) USE_SBG is 1, but mySbgSensor is not defined (because TESTING=1). That will cause issues during compilation. I don't understand yet why it compiles right now, but I'm almost sure there is some questionable logic that's happening somewhere.
2. We don't want to take the real values of radio and logger. Instead, we want to be able to take "fake values". This is important to 1 - be able to test the init state and 2 - to not have difference between the output and expected output files (because the init state could possibly finish at different times)

Because of those two things, I think that we will need to refactor the testing class. I don't think it should be an IO class. Instead, I think it should be an "helper class" that can be accessed by the multiple IOs to feed in fake data instead of real data.

**Review by sebastiengrd — CHANGES_REQUESTED** [review]
For the Interface::sensorsInitialized() method, I'm not sure about the logic when TESTING=1. I see two issues with this

1. It is possible that (for example) USE_SBG is 1, but mySbgSensor is not defined (because TESTING=1). That will cause issues during compilation. I don't understand yet why it compiles right now, but I'm almost sure there is some questionable logic that's happening somewhere.
2. We don't want to take the real values of radio and logger. Instead, we want to be able to take "fake values". This is important to 1 - be able to test the init state and 2 - to not have difference between the output and expected output files (because the init state could possibly finish at different times)

Because of those two things, I think that we will need to refactor the testing class. I don't think it should be an IO class. Instead, I think it should be an namespace or a singleton that can be accessed by the multiple IOs to feed in fake data instead of real data.

**Comment by ajayyy** [comment]
I still think faking should happen in the interface, not the individual IO classes. I'll try moving the testing stuff into a new "fake" interface, I think that will make it clearer for when testing isn't being run.

**Comment by sebastiengrd** [comment]
Yeah, I agree. When I think back at what I suggested, I finally don't think it is the best solution... I think that what is/was confusing to me is the way data flow between the IO, the interface and the SM. This is why I had the (bad) idea of faking the data in the IO. Also, there is data that we use in the logic that we don't log (for example, we change state when all the sensors are initialized, but we don't log if they are initialized for all of them). I think the best solution for this would be to make a proper diagrams and documentation on how the data should flow to clear things out.

**Comment by ajayyy** [comment]
The last issue that needs to be fixed is to take the current time to methods in the state machine library class (change state after time, etc.)

**Review by sebastiengrd — APPROVED** [review]

**Pull request merged**
