### PR TITLE
changing logging file to make it always run for sbg, values 0 and 1

### PR DESCRIPTION
**Pull request by sebastiengrd**
In the logger, we logged the state number in the middle of the line (where the sbg values were logged). 
Moving this value at the front of the line.

### CODE REVIEW

**Review by ajayyy — CHANGES_REQUESTED** [review]
Can you modify `input.txt`? Otherwise, we are testing with incorrect values.

**Comment by Renfrew100** [comment]
> Can you modify `input.txt`? Otherwise, we are testing with incorrect values.

Modify to what values in particular? I believe Roman did that but there is no set output that we are aware of when I talked to Seb last. In order to write an input.txt we need to first come up with a desired output from the list of already output files...

**Comment by sebastiengrd** [comment]
> Can you modify `input.txt`? Otherwise, we are testing with incorrect values.

I think it is working correctly even if I didn't changed input.txt. The input.txt/TestingSensor.cpp and the the output/Logger.cpp are configured in different formats. But the TestingSensor.cpp still populates the right fields of the struct when it's reading the file.

I was hesitant about modifying input.txt because I wanted to keep the same data format we had for october sky. But I can change it as well and write documentation about it.

**Comment by ajayyy** [comment]
Ah, good point. We are probably going to need to change it anyway though when we make the hotfire test test. I guess we can wait until then though.

**Review by ajayyy — APPROVED** [review]

**Pull request merged**
