### PR TITLE
Update submodules and allow actions to be run locally using act

### PR DESCRIPTION
**Pull request by SeoFernando25**
- Bumped Catch2 to 2.13.8 as the previous one 2.13.4 had issues with newer versions of GCC [see link](https://github.com/rstudio/rstudio/pull/10546)
- Modified workflows so it now be run using `act` ([A local GitHub actions runner](https://github.com/nektos/act)) [example here](https://asciinema.org/a/rihJEh6Jn1CY0LkBQqP2q8GOu)
- Allowed non-org users to build the project since [sbgECom is now open-source](https://github.com/SBG-Systems/sbgECom)

### CODE REVIEW

**Comment by jonapap** [comment]
Thanks for cleaning up the CI scripts! Also, `act` seems really cool! However, I can't get it working on my machine. Still need to debug this when I'll have time:
```
~/git/rocket-code-2020 fernando.n_refactor *6 !1 ?4 ❯ act
[End-to-end/OctoberSky1   ] 🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
[End-to-end/OctoberSky1   ]   🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform= username= forcePull=false
[End-to-end/OctoberSky1   ]   🐳  docker create image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[End-to-end/OctoberSky1   ]   🐳  docker run image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[End-to-end/OctoberSky1   ]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root workdir=
[End-to-end/OctoberSky1   ]   🐳  docker cp src=/home/jonapap/git/rocket-code-2020/. dst=/home/jonapap/git/rocket-code-2020
[End-to-end/OctoberSky1   ]   🐳  docker exec cmd=[mkdir -p /home/jonapap/git/rocket-code-2020] user= workdir=
[End-to-end/OctoberSky1   ] ⭐  Run Install SSH Key
[End-to-end/OctoberSky1   ]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /home/jonapap/git/rocket-code-2020/workflow/0] user= workdir=
| mkdir: cannot create directory '/root/.ssh': File exists
[End-to-end/OctoberSky1   ]   ❌  Failure - Install SSH Key
Error: exit with `FAILURE`: 1
```

**Comment by ajayyy** [comment]
Also, does `git config --global url.ssh://git@github.com/.insteadOf https://github.com` apply globally?

**Comment by jonapap** [comment]
I think everything is in a container. Anyway, I was dumb (really should go to sleep) and didn't checkout the proper branch. @SeoFernando25 already added that flag.

**Comment by jonapap** [comment]
Also, does anyone remember why we aren't using Ninja in the CI?

**Comment by ajayyy** [comment]
Maybe since it is only one core?

**Pull request merged**
